### ISSUE TITLE
Cannot run adult.py

### ISSUE THREAD

**Issue by eliasbenussi** [IBM/sensitive-subspace-robustness#1]
Hi,

I have been unable to run the `adult.py` script. I downloaded `adult.data`, `adult.test` and `adult.names` from UCI, and beyond removing extra white spaces in the csv files I didn't make any modifications. However, I keep getting this error:

```
On experiment 0
Traceback (most recent call last):
  File "adult.py", line 472, in <module>
    run_experiments('baseline', num_exp, path_to_save_experiments +'baseline/')
  File "adult.py", line 410, in run_experiments
    X_train, X_test, y_train, y_test, X_gender_train, X_gender_test, y_gender_train, y_gender_test, dataset_orig_train, dataset_orig_test = preprocess_adult_data(seed = i)
  File "adult.py", line 47, in preprocess_adult_data
    dataset_orig = get_adult_data()
  File "adult.py", line 36, in get_adult_data
    df.drop(delete_these, axis=1, inplace=True)
  File "/Users/me/.pyenv/versions/subspace-robust/lib/python3.7/site-packages/pandas/core/frame.py", line 4315, in drop
    errors=errors,
  File "/Users/me/.pyenv/versions/subspace-robust/lib/python3.7/site-packages/pandas/core/generic.py", line 4153, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/Users/me/.pyenv/versions/subspace-robust/lib/python3.7/site-packages/pandas/core/generic.py", line 4188, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/Users/me/.pyenv/versions/subspace-robust/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 5591, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['race_ Amer-Indian-Eskimo' 'race_ Asian-Pac-Islander' 'race_ Black'\n 'race_ Other' 'sex_ Female' 'native-country_ Cambodia'\n 'native-country_ Canada' 'native-country_ China'\n 'native-country_ Columbia' 'native-country_ Cuba'\n 'native-country_ Dominican-Republic' 'native-country_ Ecuador'\n 'native-country_ El-Salvador' 'native-country_ England'\n 'native-country_ France' 'native-country_ Germany'\n 'native-country_ Greece' 'native-country_ Guatemala'\n 'native-country_ Haiti' 'native-country_ Holand-Netherlands'\n 'native-country_ Honduras' 'native-country_ Hong'\n 'native-country_ Hungary' 'native-country_ India' 'native-country_ Iran'\n 'native-country_ Ireland' 'native-country_ Italy'\n 'native-country_ Jamaica' 'native-country_ Japan' 'native-country_ Laos'\n 'native-country_ Mexico' 'native-country_ Nicaragua'\n 'native-country_ Outlying-US(Guam-USVI-etc)' 'native-country_ Peru'\n 'native-country_ Philippines' 'native-country_ Poland'\n 'native-country_ Portugal' 'native-country_ Puerto-Rico'\n 'native-country_ Scotland' 'native-country_ South'\n 'native-country_ Taiwan' 'native-country_ Thailand'\n 'native-country_ Trinadad&Tobago' 'native-country_ United-States'\n 'native-country_ Vietnam' 'native-country_ Yugoslavia'] not found in axis"
```

Do you have any advice on what I might be doing wrong?

Thank you!

**Comment by eliasbenussi** [comment]
Apologies, I had not noticed I could run the `adult_notebook`. That's working for me.
